---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
  annotations:
    domain.type: support
    component.shared: 'true'
    component.name: keycloak
      architecture.domain: shared
      architecture.function: auth-provider
      architecture.invoked_by: access-control-app-instance
      architecture.calls: user-database
      architecture.part_of: arkit8s
  namespace: shared-components
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.4
          args:
            - start-dev
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_DB
              value: dev-mem
            - name: KC_HEALTH_ENABLED
              value: 'true'
          ports:
            - containerPort: 8080
