---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  annotations:
    architecture.domain: shared
    architecture.function: auth-provider
    architecture.invoked_by: access-control-app-instance
    architecture.calls: user-database
    architecture.part_of: arkit8s
  namespace: shared-components
spec:
  selector:
    app: keycloak
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
