apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  arkit8s.component: sentik
resources:
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - cronjob.yaml
