apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-verification
  labels:
    app: identity-verification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-verification
  template:
    metadata:
      labels:
        app: identity-verification
    spec:
      containers:
        - name: identity-verification
          image: busybox:1.36
          command: ["sh", "-c", "sleep infinity"]
