---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-identity-verification-app-instance
  labels:
    app: person-identity-verification-app-instance
  annotations:
    architecture.domain: business
    architecture.function: person-identity-verification
    architecture.invoked_by: api-app-instance
    architecture.calls: access-control-app-instance
    architecture.part_of: arkit8s
  namespace: business-domain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-identity-verification-app-instance
  template:
    metadata:
      labels:
        app: person-identity-verification-app-instance
    spec:
      containers:
        - name: person-identity-verification-app-instance
          image: registry.redhat.io/openshift4/ose-tools-rhel9
          command:
            - /bin/bash
            - -c
            - sleep infinity
          env:
            - name: PLACEHOLDER_ENV
              value: dev
