---
apiVersion: v1
kind: Service
metadata:
  name: identity-verification
  namespace: business-domain
spec:
  selector:
    app: identity-verification
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
