---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app-instance
  labels:
    app: api-app-instance
  namespace: business-domain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-app-instance
  template:
    metadata:
      labels:
        app: api-app-instance
    spec:
      containers:
        - name: api-app-instance
          image: registry.redhat.io/openshift4/ose-tools-rhel9
          command:
            - /bin/bash
            - -c
            - sleep infinity
          env:
            - name: PLACEHOLDER_ENV
              value: dev
