apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  arkit8s.part_of: arkit8s
  app-type: arkit8s
resources:
  - bootstrap
  - business-domain
  - shared-components
  - support-domain
