---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-external-services-app-instance
  labels:
    app: notification-external-services-app-instance
  annotations:
    architecture.domain: support
    architecture.function: notification
    architecture.invoked_by: orchestrator-app-instance
    architecture.calls: external-email-service
    architecture.part_of: arkit8s
  namespace: support-domain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-external-services-app-instance
  template:
    metadata:
      labels:
        app: notification-external-services-app-instance
    spec:
      containers:
        - name: notification-external-services-app-instance
          image: registry.redhat.io/openshift4/ose-tools-rhel9
          command:
            - /bin/bash
            - -c
            - sleep infinity
          env:
            - name: PLACEHOLDER_ENV
              value: dev
