apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  arkit8s.domain: support
resources:
  - address-validator
  - notification-external-services
  - data-access
  - orchestrator
  - user-profile
