---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-profile-app-instance
  labels:
    app: user-profile-app-instance
  annotations:
    architecture.domain: support
    architecture.function: user-profile
    architecture.invoked_by: api-app-instance
    architecture.calls: database
    architecture.part_of: arkit8s
  namespace: support-domain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-profile-app-instance
  template:
    metadata:
      labels:
        app: user-profile-app-instance
    spec:
      containers:
        - name: user-profile-app-instance
          image: registry.redhat.io/openshift4/ose-tools-rhel9
          command:
            - /bin/bash
            - -c
            - sleep infinity
          env:
            - name: PLACEHOLDER_ENV
              value: dev
