---
apiVersion: v1
kind: Service
metadata:
  name: identity-verification-app-instance
  annotations:
    architecture.domain: support
    architecture.function: user-profile
    architecture.invoked_by: api-app-instance
    architecture.calls: database
    architecture.part_of: arkit8s
  namespace: support-domain
spec:
  selector:
    app: identity-verification-app-instance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
