---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: address-validator-app-instance
  labels:
    app: address-validator-app-instance
  annotations:
    architecture.domain: support
    architecture.function: address-validator
    architecture.invoked_by: api-app-instance
    architecture.calls: external-address-api
    architecture.part_of: arkit8s
  namespace: support-domain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: address-validator-app-instance
  template:
    metadata:
      labels:
        app: address-validator-app-instance
    spec:
      containers:
        - name: address-validator-app-instance
          image: registry.redhat.io/openshift4/ose-tools-rhel9
          command:
            - /bin/bash
            - -c
            - sleep infinity
          env:
            - name: PLACEHOLDER_ENV
              value: dev
