---
apiVersion: v1
kind: Service
metadata:
  name: address-validator-app-instance
  annotations:
    architecture.domain: support
    architecture.function: address-validator
    architecture.invoked_by: api-app-instance
    architecture.calls: external-address-api
    architecture.part_of: arkit8s
  namespace: support-domain
spec:
  selector:
    app: address-validator-app-instance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
