---
apiVersion: v1
kind: Service
metadata:
  name: identity-verification-app-instance
  namespace: support-domain
spec:
  selector:
    app: identity-verification-app-instance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
