apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: demo-realm
  namespace: rhbk
spec:
  keycloakCRName: rhbk
  realm:
    id: demo
    realm: demo
    displayName: Demo
    enabled: true
