---
apiVersion: v1
kind: Service
metadata:
  name: company-identity-verification-app-instance
  annotations:
    architecture.domain: business
    architecture.function: company-identity-verification
    architecture.invoked_by: api-app-instance
    architecture.calls: access-control-app-instance
    architecture.part_of: arkit8s
  namespace: business-domain
spec:
  selector:
    app: company-identity-verification-app-instance
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
