apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: architects-visualization
  app.kubernetes.io/part-of: arkit8s
resources:
  - configmap-ui.yaml
  - console-commands-configmap.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
