apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: keycloak
          env:
            - name: KC_HEALTH_ENABLED
              value: "true"
