name: Build Architects Console image

on:
  push:
    branches:
      - main
    paths:
      - 'support-domain/architects-console/**'
      - 'architecture/support-domain/architects-visualization/**'
      - '.github/workflows/architects-console-build.yml'
  pull_request:
    paths:
      - 'support-domain/architects-console/**'
      - 'architecture/support-domain/architects-visualization/**'
      - '.github/workflows/architects-console-build.yml'
  workflow_dispatch:

jobs:
  verify:
    name: Build and test console module
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Run Maven verify
        run: mvn -pl support-domain/architects-console -am verify -B

  publish:
    name: Build and push container image
    needs: verify
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_PASSWORD }}
      - name: Compute image metadata
        id: meta
        run: |
          SHORT_SHA="${GITHUB_SHA::12}"
          echo "image=quay.io/arkit8s/architects-console" >> "$GITHUB_OUTPUT"
          echo "tag=$SHORT_SHA" >> "$GITHUB_OUTPUT"
      - name: Build and push image
        run: >-
          mvn -pl support-domain/architects-console -am package -B -DskipTests
          -Dquarkus.container-image.build=true
          -Dquarkus.container-image.push=true
          -Dquarkus.container-image.builder=docker
          -Dquarkus.container-image.image=${{ steps.meta.outputs.image }}
          -Dquarkus.container-image.tag=${{ steps.meta.outputs.tag }}
          -Dquarkus.container-image.additional-tags=latest
