name: Validate YAML

on:
  pull_request:
    paths:
      - '**/*.yaml'
      - 'utilities/validate-yaml.sh'
      - '.github/workflows/validate.yml'

jobs:
  yaml-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run YAML validation
        run: |
          chmod +x utilities/validate-yaml.sh
          ./utilities/validate-yaml.sh
