name: Validate YAML and Python

on:
  pull_request:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.py'
      - 'utilities/validate-yaml.sh'
      - '.github/workflows/validate.yml'
      - 'support-domain/architects-console/**'

jobs:
  detect-changes:
    name: Detect file changes
    runs-on: ubuntu-latest
    outputs:
      architects_console: ${{ steps.filter.outputs.architects_console }}
    steps:
      - uses: actions/checkout@v3
      - id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            architects_console:
              - 'support-domain/architects-console/**'

  yaml-validation:
    name: YAML syntax validation
    runs-on: ubuntu-latest
    needs:
      - detect-changes
    steps:
      - uses: actions/checkout@v3
      - name: Run YAML validation
        run: |
          chmod +x utilities/validate-yaml.sh
          ./utilities/validate-yaml.sh

  yaml-lint:
    name: YAML linting
    runs-on: ubuntu-latest
    needs:
      - detect-changes
    steps:
      - uses: actions/checkout@v3
      - name: Install yamllint
        run: |
          python3 -m pip install --user yamllint
      - name: Run yamllint
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          yamllint -d "{extends: default, rules: {line-length: disable}}" .

  python-compilation:
    name: Python compilation check
    runs-on: ubuntu-latest
    needs:
      - detect-changes
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Compile Python files
        run: python -m compileall .

  architects-console-build:
    name: Architects Console build and tests
    runs-on: ubuntu-latest
    needs:
      - detect-changes
    if: needs.detect-changes.outputs.architects_console == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven
      - name: Build and test module
        run: mvn -pl support-domain/architects-console -am clean verify -B

  automerge:
    name: Enable auto-merge (no architects-console changes)
    needs:
      - detect-changes
      - yaml-validation
      - yaml-lint
      - python-compilation
    if: |
      github.event.pull_request.head.repo.full_name == github.repository &&
      needs.detect-changes.outputs.architects_console != 'true'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          pull-request-number: ${{ github.event.pull_request.number }}
      - name: Delete PR branch on merge
        uses: actions/github-script@v6
        with:
          script: |
            const result = await github.graphql(`
              mutation($input: UpdatePullRequestInput!) {
                updatePullRequest(input: $input) {
                  pullRequest {
                    number
                  }
                }
              }
            `, {
              input: {
                pullRequestId: '${{ github.event.pull_request.node_id }}',
                deleteHeadRefOnMerge: true
              }
            });
            const pullRequest = result?.updatePullRequest?.pullRequest;
            if (!pullRequest?.number) {
              core.setFailed('Failed to enable PR head branch deletion.');
            }

  automerge-with-architects:
    name: Enable auto-merge (with architects-console build)
    needs:
      - detect-changes
      - yaml-validation
      - yaml-lint
      - python-compilation
      - architects-console-build
    if: |
      github.event.pull_request.head.repo.full_name == github.repository &&
      needs.detect-changes.outputs.architects_console == 'true'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
          pull-request-number: ${{ github.event.pull_request.number }}
      - name: Delete PR branch on merge
        uses: actions/github-script@v6
        with:
          script: |
            const result = await github.graphql(`
              mutation($input: UpdatePullRequestInput!) {
                updatePullRequest(input: $input) {
                  pullRequest {
                    number
                  }
                }
              }
            `, {
              input: {
                pullRequestId: '${{ github.event.pull_request.node_id }}',
                deleteHeadRefOnMerge: true
              }
            });
            const pullRequest = result?.updatePullRequest?.pullRequest;
            if (!pullRequest?.number) {
              core.setFailed('Failed to enable PR head branch deletion.');
            }
