name: Validate YAML

on:
  pull_request:
    paths:
      - '**/*.yaml'
      - 'utilities/validate-yaml.sh'
      - '.github/workflows/validate.yml'

jobs:
  yaml-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          version: 'stable'
      - name: Login to cluster
        if: env.OPENSHIFT_SERVER != '' && env.OPENSHIFT_TOKEN != ''
        run: oc login "$OPENSHIFT_SERVER" --token "$OPENSHIFT_TOKEN" --insecure-skip-tls-verify
      - name: Run YAML validation
        run: |
          chmod +x utilities/validate-yaml.sh
          ./utilities/validate-yaml.sh
